name: Deploy Python Lambda to AWS

on:
  push:
    branches:
      - main  # Deploys on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and package Lambda
        run: |
          mkdir -p package
          if [ -s requirements.txt ]; then
            pip install -r requirements.txt -t package/
          fi
          cp lambda_function.py package/
          cd package
          zip -r ../lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:889937330363:function:TestFuction
            --zip-file fileb://lambda.zip
